### ISSUE TITLE
Update to Tasmota 12.1.1?

### ISSUE THREAD

**Issue by sthufnagl** [gkle/tasmota-sip#1]
Hi,
let me say "great work"! I integrated your code into a Tasmota WebCam.
:-)
Would it be possible to update the code to Tasmota 12.1.1? 
If you need a helping hand let me know...

Cheers

Steve

**Comment by gkle** [comment]
Done

**Comment by sthufnagl** [comment]
Thx
:-)

**Comment by sthufnagl** [comment]
Hi,
I tested your code with the new version, but I have no luck with Tasmota 12.2.0. I did everything you described...without the 
#define USE_SIP inside "user_config_override.h" it works.

The compile error is:
_**C:/Users/hufna/Downloads/Tasmota-development (1)/Tasmota-development/tasmota/tasmota_xx2c_global/xdrv_interface.ino:391:3: error: invalid conversion from 'bool (*)(uint8_t)' {aka 'bool (*)(unsigned char)'} to 'bool (*)(uint32_t)' {aka 'bool (*)(unsigned int)'} [-fpermissive]
   &Xdrv92,**_

Thx in advance

Steve
