### ISSUE TITLE
Compile Errors with Tasmota 12.2.0

### ISSUE THREAD

**Issue by sthufnagl** [gkle/tasmota-sip#2]
Hi,
I tested your code with the new version, but I have no luck with Tasmota 12.2.0. I did everything you described.
Without the statement "#define USE_SIP inside "user_config_override.h"" I'm able to compile Tasmota 12.2.
BTW, Tasmota 9.3.1 works fine.

**The compile error is:**
**_C:/Users/hufna/Downloads/Tasmota-development (1)/Tasmota-development/tasmota/tasmota_xx2c_global/xdrv_interface.ino:391:3: error: invalid conversion from 'bool ()(uint8_t)' {aka 'bool ()(unsigned char)'} to 'bool ()(uint32_t)' {aka 'bool ()(unsigned int)'} [-fpermissive]
&Xdrv92,_**

Thx in advance

Steve

**Comment by sthufnagl** [comment]
Hi,
it seems that the compile error is related to the new Tasmota Version 12.2.0 ...Tasmota 12.1.1 works. 

Currently I test 12.1.1 on a WT32-Eth01 Board, very intersting because the LAN/Ethernet didn't work with your SIP Driver.
May be 9.3.1 has still Problems with LAN. WIFI works.

I would like to keep the Issue open because of the 12.2.0 Problem, I hope you don't mind.
Thx

Steve

**Comment by sthufnagl** [comment]
...regarding LAN Problem...it was the Tasmota 9.3.1. WIth Tasmota 12.1.1 the SIP Call over LAN works!
:-)
I will use your Code as a source of valueable information "how to create an "XDRV Driver".
:-)
Thx

**Comment by gkle** [comment]
I had no compile error with Tasmota V12.2.0
Try updating PlatformIO. I'm using Core 6.1.5 Home 3.4.3
Start with a clean branch from current master.
I do not know about WT32-Eth01 board. I dont think that the LAN/Ethernet is implemented as IP interface.
Note that the wifi interface must be ready for sip communication. 
Have a look at
            if (WL_CONNECTED != Wifi.status) {
                return false; // wait until wiffi is ready
            }

**Comment by sthufnagl** [comment]
Hi,

thanks for the fast reply. My Environment is the same like yours...may be the reason

was a Code Change in the new Tasmota Interface Definition.

**Sip Drvx:**

- There is a Tasmota code change inside xdrv_interface.ino 
- **from 12.1.1...**

_#ifdef XFUNC_PTR_IN_ROM
bool (* const xdrv_func_ptr[])(uint8_t) PROGMEM = {   // Driver Function Pointers
#else
bool (* const xdrv_func_ptr[])(uint8_t) = {   // Driver Function Pointers
#endif_

**...to 12.2.2**
_#ifdef XFUNC_PTR_IN_ROM
bool (* const xdrv_func_ptr[])(uint32_t) PROGMEM = {   // Driver Function Pointers
#else
bool (* const xdrv_func_ptr[])(uint32_t) = {   // Driver Function Pointers
#endif_

**After changing the related code of your xdrv_92_sip.ino**
   from line 473
        bool Xdrv92(uint8_t function) 
   to
        bool Xdrv92(uint32_t function) 
  I was able to compile. Not sure if we get now some sideeffects?

Thanks and I hope this was the reason...
:-)

Stefan

**Comment by sthufnagl** [comment]
Everything works fine with the minor change...
Thx
